name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name 'Mitch McAffee'
      - run: git config --global user.email 'themcaffee@users.noreply.github.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push